spring.application.name=demo



spring.datasource.url=jdbc:mariadb://192.168.0.228:3306/cafe_erp
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.example

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp